version: "3.3"
services:
  caddy:
    container_name: caddy
    image: caddy:alpine
    restart: always
    volumes:
      - /persist/caddy:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /admin-page:/admin-page
    ports:
      - "443:443"
      - "80:80"
    networks:
      - default_network
  basic-service:
    container_name: basic-service
    image: wwricu/basic-service:snapshot
    restart: always
    expose:
      - "8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /persist/basic:/data
    networks:
      - default_network
  blog-page:
    container_name: blog-page
    image: wwricu/blog-page:snapshot
    restart: always
    expose:
      - "3000"
    environment:
      - NEXT_BASE_URL=http://basic-service:8000
    networks:
      - default_network
  v2ray:
    container_name: v2ray
    image: v2fly/v2fly-core:latest
    restart: always
    expose:
      - "8443"
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
      - /persist/v2ray/log:/var/log/v2ray
    command: run -config /etc/v2ray/config.json
    networks:
      - default_network
networks:
  default_network:
