name: Deploy snapshot
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOSTNAME }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            mkdir /data
            mkdir /data/v2ray
            rm -rf /data/deploy
            mkdir /data/deploy
      - uses: actions/checkout@v4
      - run: |
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          sed -i "s/{V2RAY_UID}/${{ secrets.V2RAY_UID }}/g" v2ray/config.json
          wget https://github.com/wwricu/admin-page/releases/download/snapshot/dist.tar.gz
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOSTNAME }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "."
          target: "/data/deploy"
          overwrite: true
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOSTNAME }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist.tar.gz"
          target: "/data/admin"
          overwrite: true
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOSTNAME }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker rm -f $(docker ps -aq)
            docker rmi wwricu/basic-service:snapshot
            docker rmi wwricu/admin-page:snapshot
            docker rmi wwricu/blog-page:snapshot
            cd /data/deploy
            docker-compose -f docker-compose-dev.yml up -d
