name: Deploy dev
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            rm -rf /deploy
            mkdir /deploy
      - uses: actions/checkout@v4
      - run: |
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo ENV=dev >> .env
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "."
          target: "/deploy"
          overwrite: true
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker rm -f $(docker ps -aq)
            cd /deploy
            docker-compose up -d
